### ISSUE TITLE
Hosted service is down

### ISSUE THREAD

**Issue by nexdrew** [afeld/jsonp#100]
Hi! 👋 This is a really cool service and I appreciate you letting open source folks use it for free!

I recently started using it for [the yargs docs site](http://yargs.js.org/docs/index.html) so that the browser could query the public npm registry (which does not support CORS) to determine the `latest` published version of yargs in order to render the README for the appropriate tag (instead of always using the master branch, which could be ahead of `latest`) via [Flatdoc](https://github.com/rstacruz/flatdoc).

Anyway, I noticed the service was down today (CloudFlare returns a non-JSONP 521 response for our particular request) which meant our docs were unavailable. I have since [patched around](https://github.com/yargs/yargs.github.io/pull/24) this issue, but I was wondering what your short and long term goals for this project are? I.E. do you plan to keep it running as a free service? It seems like you have put a decent amount of thought/work into this, so I'd hate to see it go away.

Regardless, thanks for building this useful service!

**Comment by afeld** [comment]
Hey, sorry about that. I don't have a lot of time to dedicate to this right now, so will get to it as soon as I can. Would love some infrastructure help from anyone reading this!

**Comment by afeld** [comment]
Back up now, sorry about that! I have a better understanding of the new deployment environment now (#101), so _should_ be better going forward.

**Comment by bradyswenson** [comment]
Thanks again @afeld!

**Comment by nexdrew** [comment]
Agreed, thanks so much @afeld!

**Comment by estevet** [comment]
Just like @bradyswenson and @nexdrew I add myself to the Thank you note.

The service seems to be down. Can I be of any help? (thanks in advance!)

**Comment by afeld** [comment]
I'm currently running it on Kubernetes, but don't have time to investigate the current issue. If someone has experience here or would like to learn, please reach out!

**Comment by pcsandford** [comment]
@afeld it looks like the hosting service is currently down again. Do you have an ETA on when it will be back up? Thanks!

**Comment by antons-** [comment]
@afeld The hosting service is down at the moment, will this be resolved soon?

**Comment by patw0929** [comment]
Down again more than 1 day, please help to fix. Thank you.

**Comment by nexdrew** [comment]
FYI for folks using this service - you can also use https://json2jsonp.com as a backup/alternative - they share the same API. [Here's an example](https://github.com/yargs/yargs.github.io/blob/c25affe46aa70ba90480bf0a549abfbced0f5b8a/_layouts/docs.html#L31-L64) of some jQuery client code that tries one and falls back to the next.

**Comment by afeld** [comment]
Sorry folks - app seems to be unreliable, no matter where I host it, and I clearly haven't been giving it much focus. #112 and #109 would help, if anyone is interested.

**Comment by afeld** [comment]
Back up (now on Lambda) - sorry about the delay!
