### ISSUE TITLE
"Failed to load resource: the server responded with a status of 504 ()"

### ISSUE THREAD

**Issue by bradyswenson** [afeld/jsonp#108]
Getting this error trying to connect to Medium's JSON API. 

Here's the URL being called: https://jsonp.afeld.me/?callback=jQuery22308919072617129755_1484687365366&url=https://medium.com/crossroads-communication?format=json&_=1484687365367

![image](https://cloud.githubusercontent.com/assets/3144456/22040114/60b3dbf6-dcc7-11e6-8861-9d1b9a20f3f1.png)

**Comment by afeld** [comment]
Closing as stale - sorry for not responding sooner. Let me know if this is still an issue.
