### ISSUE TITLE
use functions as a service

### ISSUE THREAD

**Issue by afeld** [afeld/jsonp#109]
This app is basically the perfect candidate for it.

* https://aws.amazon.com/lambda/
* https://cloud.google.com/functions/
* https://azure.microsoft.com/en-us/pricing/details/functions/
* https://stdlib.com/
* https://serverless.com/
    * https://github.com/serverless/serverless-google-cloudfunctions
    * https://github.com/postlight/serverless-babel-starter
* https://arc.codes/

Considerations:

* Limiting throughput/expense
* Cost

**Comment by afeld** [comment]
Converting the proxy to a "serverless" app would be nice because it seems to have a memory leak or something that causes the app to be unresponsive after a while, no matter what I have tried. Having each request handled in an isolated space totally sidesteps that problem.

**Comment by nexdrew** [comment]
Could possibly look into [Zeit's Now](https://zeit.co/now) virtualized hosting as well. From my limited experience with it, it behaves like a serverless, "run on demand/request" solution, but doesn't require you to completely overhaul the architecture of the app. Not sure if it's a good fit for this project or not, but just throwing it out there.
