### ISSUE TITLE
HTTP error, 525: SSL handshake failed

### ISSUE THREAD

**Issue by lastmjs** [afeld/jsonp#148]
Hey there,

I'm getting 525: SSL handshake failed returned with the following request:

`https://jsonp.afeld.me/?url=https://intotheether.libsyn.com/rss`

I think it's happening to me on some other urls as well. Seems like an issue with the hosted proxy.

**Comment by afeld** [comment]
Hmm. The good news is that I also get an error locally:

![screen shot 2019-03-04 at 11 01 43 pm](https://user-images.githubusercontent.com/86842/53780256-93c8ad00-3ed1-11e9-8179-a59bb72e4c3c.png)

The bad news is that error seems like it may be different, and I'm not sure if either are an issue on the JSONProxy end or their end.

**Comment by lastmjs** [comment]
I think it's on JSONProxy end, using cors-anywhere, https://cors-anywhere.herokuapp.com, in my app, seems to work fine.

**Comment by afeld** [comment]
The proxy is deployed on CloudFlare. Given that [this documentation](https://support.cloudflare.com/hc/en-us/articles/200278659-Error-525-SSL-handshake-failed) basically says "it's a problem on the origin side". Very possible that CloudFlare does something more strict around certificates than Heroku...? Whether that's actually the case or not, not sure what else I can do. Sorry!
