### ISSUE TITLE
hosting my own proxy - getting a script loading error  with JSONP - firefox only

### ISSUE THREAD

**Issue by dtenenba** [afeld/jsonp#157]
Hi,

I forked the repo (https://github.com/FredHutch/jsonp) and I am running my own proxy at 
https://wiki-json-proxy.fhcrc.org/ . I did remember to change `PROXY` to my host's URL.

The proxy fails to work ONLY when ALL of the following are true:

* when used in javascript (as opposed to curl or putting a URL in a browser) 
* when run in Firefox (Safari and Chrome are OK); this is Firefox 66.0.5 on macOS 10.14.4
* when using my hosted/forked version. If I use `jsonp.afeld.me` it works fine even when the above conditions are true.

Here is the web page in question:

```html
<html>
<head>
</head>
<body>
    <h1>hi</h1>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        $(function () {
            console.log("jquery ready!");
            $.getJSON('https://wiki-json-proxy.fhcrc.org/?callback=?&url=https://jsonview.com/example.json', function (data) {
                console.log(data);
            });
        });
    </script>
</body>
</html>
```

On Firefox I see the following in the Javascript console:

```
jquery ready!
Loading failed for the <script> with source “https://wiki-json-proxy.fhcrc.org/?callback=jQuery34107701057441717892_1558153068486&url=https://jsonview.com/example.json&_=1558153068487”.
```

Any ideas what's going on? I turned off all my browser extensions so they are not the problem. Same thing happens in regular windows & private windows.

**Comment by afeld** [comment]
Hmm, I wasn't able to reproduce (using Firefox 66.0.5). Can you get someone else with Firefox to try? Going to close for now, but we can reopen if it seems like something on JSONProxy's end.
