### ISSUE TITLE
request library returning an empty body on 50% of soundcloud links

### ISSUE THREAD

**Issue by LiamBigelow** [afeld/jsonp#17]
On calls to api.soundcloud.com through the proxy (exactly?) 50% of the time an empty body is returned, resulting in ```{"error":""}```

This problem can be replicated on the following domain

https://jsonp.jit.su/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F28698952%3Fclient_id%3Dapigee

Reloading causes the inverse of the current result.

Fixed by replacting request module with needle module.

Working fix:

https://seam.li/json/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F28698952%3Fclient_id%3Dapigee

request replaced with needle. 

Cause unknown.

**Comment by afeld** [comment]
Closing as stale – let me know if you continue to see the problem.
