### ISSUE TITLE
status: 403

### ISSUE THREAD

**Issue by ux33-331** [afeld/jsonp#179]
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

I get this response when visiting https://jsonp.afeld.me

**Comment by afeld** [comment]
Yeeeeah, got this email from CloudFlare a few days ago:

> Cloudflare has deactivated your website, afeld.me, because of a possible violation of the Terms of Service for the storage or caching of non-HTML content, such as video or audio files.

referring to Section 2.8 of their [Terms](https://www.cloudflare.com/terms/). Considering which of the following to do about it:

- Contact CloudFlare and ask for an exception
- Move off of CloudFlare
- Decide the site's had a good run and shut it down
   - Costing me more than I want to spend every month anyway, considering zero revenue

**Comment by niutech** [comment]
Please don't kill this very useful service. Is is being used by HTMLPreview to help previewing GitHub repositories. Could you please whitelist only non-binary file requests (HTML/CSS/JS/SVG/TXT) and ask Cloudflare if they can restore the service? Thanks!

**Comment by gavinr** [comment]
I too was using this and came here only when it stopped working (like a freeloader). Totally respect your decision to shut it down. **Thank you** for the multiple years of keeping it running! 👍

**Comment by ux33-331** [comment]
Hopefully CloudFlare can make an exception for your awesome site.. Totally respect your decision if you decide to shut down if you do but seems like there are a lot of people using your site still. Thanks for an awesome site btw!

**Comment by gavinr** [comment]
Seems like this started working again?

**Comment by afeld** [comment]
Closing, as this issue has resolved itself.
