### ISSUE TITLE
App regularly becomes unavailable 

### ISSUE THREAD

**Issue by afeld** [afeld/jsonp#18]
The app hosted on Nodejitsu seems to get into some state every three weeks or so where it starts returning "502 - Reached max retries limit".  My first thought was that there is a memory leak in the app, which I would think would be resolved by restarting the app through the Nodejitsu control panel, but this doesn't fix it.  Redeploying the app solves the problem consistently.  I see messages like this repeatedly in the logs:

```
[err] Tue, 21 Jan 2014 23:18:43 GMT FATAL ERROR:
[err] Tue, 21 Jan 2014 23:18:43 GMT Evacuation Allocation failed - process out of memory
```

:grimacing: Ideas appreciated!

/cc @bchelli

**Comment by al-the-x** [comment]
Your screenies from New Relic indicate a slow memory leak for sure. Just browsing through the code, I wonder if [the money patch to `res.send`](https://github.com/afeld/jsonp/blob/master/server/jsonp.js#L62-70) is the culprit, since it's being applied with every cycle AND creates a new closure...? If there was a partial reference to that monkey patched object lying around... Any insight into the memory heap at the crash point?

**Comment by al-the-x** [comment]
Perhaps a little `console.info` when you call `gc` would also be helpful as a sanity check?

https://github.com/afeld/jsonp/blob/master/server/proxy-request.js#L54

**Comment by afeld** [comment]
> I wonder if the money patch to res.send is the culprit

Iiiiiinteresting hypothesis. Certainly possible!

> a little `console.info` when you call `gc` would also be helpful as a sanity check

Done: https://github.com/afeld/jsonp/pull/50. `gc()` calls seem to be "working" :confounded: 

---

@al-the-x If you would be interested in doing some live debugging, email me (first dot last at gmail) – happy to give you access.

**Comment by al-the-x** [comment]
Pinged you via email, @afeld. Happy to take a look with you. Maybe also try a deployment on Heroku, to test a different deployment environment...?

**Comment by afeld** [comment]
[Moving to a new host](https://github.com/afeld/jsonp/issues/48) may help this :fingerscrossed:

**Comment by afeld** [comment]
Seems to be doing much better now – leave a comment if you have any issues.

**Comment by al-the-x** [comment]
Guess it was a case of "bad jitsu"... :D
