### ISSUE TITLE
Redirect users to new jsonp location

### ISSUE THREAD

**Issue by indexzero** [afeld/jsonp#52]
@afeld we see a fair amount of Tweets to @nodejitsu (e.g. https://twitter.com/jmayer881/status/577898590175133698) whenever something changes to `jsonp.nodejitsu.com`. I would suggest having the existing URL return something about redirecting to the new Heroku-based deployment

**Comment by afeld** [comment]
For sure. Will do as part of https://github.com/afeld/jsonp/issues/48. Thanks!

**Comment by afeld** [comment]
P.S. Sorry that you get the flak!
