### ISSUE TITLE
only validate JSON for JSONP requests

### ISSUE THREAD

**Issue by afeld** [afeld/jsonp#65]
Basically, sidestep the need for `raw=true`. Since there isn't a security issue with responding with non-JSON for normal AJAX requests, we can skip the validation, and let the client deal with the response.

**Comment by OliverJAsh** [comment]
:+1: Yes, XHRs can of course be used to fetch any data…

**Comment by afeld** [comment]
Not sure when I'll get to this – pull requests welcome :wink:
