### ISSUE TITLE
Working over https

### ISSUE THREAD

**Issue by kerri-anne** [afeld/jsonp#68]
Hi

We are trying to get the app working on https and are running in to a few issues. We can change the port but we can't seem to get it to serve. Do you have any advice?

Thanks

**Comment by afeld** [comment]
Can you elaborate on what you're seeing? Looking fine here:

https://jsonp.afeld.me/?url=http://jsonview.com/example.json

**Comment by kerri-anne** [comment]
Apologies - we are attempting to set this up on our servers so for our custom url. Is this possible?


-------- Original Message --------

**Comment by afeld** [comment]
I'm achieving this for https://jsonp.afeld.me/ by putting [CloudFlare](https://www.cloudflare.com/) in front of it as a proxy. I've never actually set up Node to serve HTTPS end-to-end, but it seems very doable with only a small change to the [app](https://github.com/afeld/jsonp/blob/master/server/app.js) if you wanted to go that way:

* http://expressjs.com/api.html#app.listen
* https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

Let me know how it goes!

**Comment by kerri-anne** [comment]
Thank you so much this is exactly what we need - we now have it running off a port on our server! You are magic thank you for making this :)
