### ISSUE TITLE
jsonp.afeld.me Application Error

### ISSUE THREAD

**Issue by onlineth** [afeld/jsonp#69]
It looks like the website, https://jsonp.afeld.me/,  is currently down,

> **Application Error**

> An error occurred in the application and your page could not be served. Please try again in a few moments.

> If you are the application owner, check your logs for details.

 ![Application Error Message](http://s3.postimg.org/ktdppk2yr/Application_Error.png)

**Comment by onlineth** [comment]
And it now appears to be up:)

**Comment by onlineth** [comment]
It's down, again

**Comment by acarridice** [comment]
Yep. It's down. Do you need donations to upgrade hosting?

**Comment by onlineth** [comment]
I would consider openshift - it's free and backed by redhat

**Comment by afeld** [comment]
The problem isn't hosting...the problem is that it was effectively being DDoSed :unamused: Should be up now (have a hack in place to block the particular request, but need to put better protection in place.

/cc https://github.com/afeld/jsonp/issues/70
