### ISSUE TITLE
make proxy URL configurable

### ISSUE THREAD

**Issue by afeld** [afeld/jsonp#7]
Some people may not trust http://jsonp.jit.su and want to host their own.

**Comment by afeld** [comment]
...or support it being set to `null` to skip proxying.

**Comment by voylinux** [comment]
How would it be possible to use that on a custom domain?
How should one configure the server?

Thanks.

**Comment by afeld** [comment]
Yep, that would be exactly the use case. No special config needed on the server side would be required, besides deploying it.
