### ISSUE TITLE
Problem With Long URLs Or Many Parameters ?

### ISSUE THREAD

**Issue by laniltee** [afeld/jsonp#89]
Is this not working when URL is too long or Is there a limitations for no.of parameters of the URL when using this. This is working perfectly for many URLs, but when the URL is too long I'm getting error messages from my API

**Comment by afeld** [comment]
Hmm...URLs have a length limit of [~2000 characters](http://stackoverflow.com/a/417184)...was it longer than that? Do you have an example?

**Comment by laniltee** [comment]
Thank you very much. I saw your solution at stackoverflow. http://stackoverflow.com/questions/34256581/jsonproxy-at-http-jsonp-afeld-me-error 
Cheers.

**Comment by afeld** [comment]
:rocket:
